### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by unicodeveloper** [andela-kerinoso/open-source-evangelists#4]
The description of the package in the readme file is misleading..

> This package encourages programmers to contribute more to open source by ranking an individual based on the number of public repositories s(he) possesses on GitHub. An individual is ranked to one of these categories:
> 
> 5 <= Junior Evangelist <= 10
> 
> 11 <= Associate Evangelist <= 20
> 
> 21 <= Most Senior Evangelist

All i see is <= which means less than or equal to 

The conditions specified in the checkpoint were  >= 5 and <=10 Junior Evangelist

> = 11 and <= 20 Associalte Evangelist
> = 21 Most Senior Evangelist

**Comment by kola-er** [comment]
This issue has been resolved.
