### ISSUE TITLE
getenv() functionality

### ISSUE THREAD

**Issue by unicodeveloper** [andela-kerinoso/open-source-evangelists#7]
I'm so excited that you used .env files to store your credentials. I looked into your composer.json and i didn't see where you required the `vlucas/phpdotenv` package. So how did it work without doing that?
I know you can use `getenv()` by default to get PHP environment variables like `REMOTE_USER`, `SERVER_NAME`  but not values from `.env` files e.t.c

**Comment by kola-er** [comment]
I had no idea, until now, that `getenv()` can't get environment variables from .env file on its own. As a matter of fact, your comment has resolved the issue I had in getting environment variables in another project. Unfortunately, I still don't know why it works here without `vlucas/phpdotenv` package. Anyway, I have required it and and also used it in my code. Thank you.
